/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js conventions and should remain committed.
// See https://nextjs.org/docs/app/api-reference/config/typescript for details.
